#
# Module manifest for module 'Home-Assistant'
#
# Generated by: Flemming Sørvollen Skaret
#
# Generated on: 11.06.2019
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'NetDaemonPs.psm1'

# ModuleVersion ignore this, but this is required
ModuleVersion = '0.0.0'

# Author of this module
Author = 'Jeff Hamm'

FunctionsToExport = @(
    '*NetDaemon*',
    )
}
